# Generated by Django 4.2.2 on 2023-06-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_subscriber'),
        ('account', '0003_remove_account_last_name_remove_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(to='schedule.course'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'мужчина'), ('женщина', 'женщина')], default='мужчина', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='account/default_icon.png', upload_to='account/%Y/%m/%d'),
        ),
    ]
