# Generated by Django 4.2.2 on 2023-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_gender_account_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='account/default_icon.png', upload_to='account/%Y/%m/%d'),
        ),
    ]
