# Generated by Django 4.2.2 on 2023-06-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_patronymic_alter_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'мужчина'), ('женщина', 'женщина')], default='мужчина', max_length=255),
        ),
    ]
