# Generated by Django 4.2.2 on 2023-06-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('duration_days', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(to='account.course'),
        ),
    ]
