# Generated by Django 4.2.2 on 2023-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_subscriber'),
        ('account', '0008_course_account_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(to='schedule.course'),
        ),
    ]
