# Generated by Django 4.2.2 on 2023-06-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_course_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
    ]
