# Generated by Django 4.2.2 on 2023-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=200, null=True)),
                ('full_description', models.TextField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('duration_days', models.PositiveIntegerField(null=True)),
                ('course_image', models.ImageField(blank=True, upload_to='images/courses')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
                'ordering': ['time_create'],
            },
        ),
    ]
