# Generated by Django 4.2.2 on 2023-06-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tag_alter_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tag'),
        ),
    ]
