# Generated by Django 4.2.2 on 2023-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.TextField(default='https://www.youtube.com/embed/D-UmfqFjpl0'),
        ),
    ]
