# Generated by Django 4.2.2 on 2023-06-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submitcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitcourse',
            name='course_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
