# Generated by Django 4.2.2 on 2023-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_submitcourse_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitcourse',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
