# Generated by Django 4.2.2 on 2023-06-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Уроки курсов', 'verbose_name_plural': 'Уроки курсов'},
        ),
    ]
