# Generated by Django 4.2.2 on 2023-06-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_lesson_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_length',
            field=models.CharField(max_length=8),
        ),
    ]
